// Generated by gencpp from file rotate_translate/OutputType.msg
// DO NOT EDIT!


#ifndef ROTATE_TRANSLATE_MESSAGE_OUTPUTTYPE_H
#define ROTATE_TRANSLATE_MESSAGE_OUTPUTTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rotate_translate
{
template <class ContainerAllocator>
struct OutputType_
{
  typedef OutputType_<ContainerAllocator> Type;

  OutputType_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  OutputType_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::rotate_translate::OutputType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rotate_translate::OutputType_<ContainerAllocator> const> ConstPtr;

}; // struct OutputType_

typedef ::rotate_translate::OutputType_<std::allocator<void> > OutputType;

typedef boost::shared_ptr< ::rotate_translate::OutputType > OutputTypePtr;
typedef boost::shared_ptr< ::rotate_translate::OutputType const> OutputTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rotate_translate::OutputType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rotate_translate::OutputType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rotate_translate::OutputType_<ContainerAllocator1> & lhs, const ::rotate_translate::OutputType_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rotate_translate::OutputType_<ContainerAllocator1> & lhs, const ::rotate_translate::OutputType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rotate_translate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rotate_translate::OutputType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rotate_translate::OutputType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotate_translate::OutputType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotate_translate::OutputType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotate_translate::OutputType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotate_translate::OutputType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rotate_translate::OutputType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::rotate_translate::OutputType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::rotate_translate::OutputType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rotate_translate/OutputType";
  }

  static const char* value(const ::rotate_translate::OutputType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rotate_translate::OutputType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
;
  }

  static const char* value(const ::rotate_translate::OutputType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rotate_translate::OutputType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OutputType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rotate_translate::OutputType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rotate_translate::OutputType_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROTATE_TRANSLATE_MESSAGE_OUTPUTTYPE_H
